version: '3'

services:
  magento23072:
    build:
      context: ./magento
      dockerfile: Dockerfile_image_7.2
    container_name: docker-magento-multiple_magento_2.3.0_7.2_1
    ports:
      - 23072:80
    depends_on:
      - db
    environment:
      MAGENTO_URL: http://magento23072.com:23072/
      MYSQL_DATABASE: magento23072
    env_file:
      - .env
    volumes:
      - ./src/230:/var/www/html
    networks:
      webnet:

  varnish:
    build: ./varnish
    ports:
      - 6082:6082
    volumes:
      - ./varnish/230.default.vcl:/etc/varnish/default.vcl
    depends_on:
      - magento23072
    links:
      - magento23072
    networks:
      webnet:

networks:
  webnet:
