version: '3'

services:
  magento23072:
    build:
      context: ./magento
      dockerfile: Dockerfile_image_7.2
    container_name: docker-magento-multiple_magento_2.3.0_7.2_1
    ports:
      - 23072:80
    depends_on:
      - db
    environment:
      MAGENTO_URL: http://magento23072.com:23072/
      MYSQL_DATABASE: magento23072
    env_file:
      - .env
    volumes:
      - ./src/230:/var/www/html
    networks:
      webnet:
networks:
  webnet:
