version: '3'

services:
  db:
    build: ./data
#    image: ngovanhuy0241/docker-magento-multiple-db
    container_name: docker-magento-multiple_db_1
#    volumes:
#      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 2122:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet
networks:
  webnet:
