version: '3'

services:
  php70:
    build:
      context: ./magento
      dockerfile: Dockerfile_7.0
    ports:
      - 19310:80
    depends_on:
      - db
    env_file:
      - .env
    networks:
      webnet:
networks:
  webnet:
