version: '3'

services:
  db:
    build: ./data
    container_name: docker-magento-multiple_db_1
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 2122:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet
networks:
  webnet:
