version: '3'

services:
  magento22671:
    build:
      context: ./magento
      dockerfile: Dockerfile_7.1
    ports:
      - 22671:80
    depends_on:
      - db
    environment:
      - MAGENTO_URL=http://magento2.com:22671/
      - MYSQL_DATABASE=magento22671
    env_file:
      - .env
    volumes:
      - ./src/2.2.6:/var/www/html
    networks:
      webnet:
networks:
  webnet:
